schedules:
- cron: 0 10 * * *
  displayName: 🟣Every day at 10:00 UTC
  branches:
    include:
    - main
  always: true

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
- name: system.debug
  value: true
- name: azureSubscriptionForStage1Download
  value: 'SourceDotNet Stage1 Publish'
- name: webAppName
  value: 'netsourceindexprod'
- name: resourceGroupName
  value: 'source.dot.net'

# Note: the subscription name variables need to be at the pipeline level to be used in the AzureCLI tasks.
#       that's because the tasks get looked at very early in the pipeline processing.
#       Also, make sure to use the template expression syntax ${{ }}
#       Issue: https://github.com/microsoft/azure-pipelines-tasks/issues/14365#issuecomment-2286398867

- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/main')) }}:
  - name: poolName
    value: 'NetSourceIndexProd-Pool'
  - name: azureSubscriptionForStorageAndWebAppSlot
    value: 'NetSourceIndex-Prod'
  - name: isOfficialBuild
    value: True
  - name: temporaryDeploymentSlot
    value: 'staging'
  - name: storageAccountName
    value: 'netsourceindexprod'
  - name: stagingHost
    value: 'staging.source.dot.net'
- ${{ else }}:
  - name: poolName
    value: 'NetSourceIndexValid-Pool'
  - name: azureSubscriptionForStorageAndWebAppSlot
    value: 'NetSourceIndex-Validation-Prod'
  - name: isOfficialBuild
    value: False
  - name: temporaryDeploymentSlot
    value: 'validation'
  - name: storageAccountName
    value: 'netsourceindexvalidprod'

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    settings:
      networkIsolationPolicy: Permissive,CFSClean2
    pool:
      name: ${{ variables.poolName }}
      image: 1es-pt-agent-image
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: stage
      jobs:
      - job: BuildIndex
        displayName: Build Source Index
        timeoutInMinutes: 360

        templateContext:
          outputs:
          - output: nuget
            displayName: 'NuGet push'
            packageParentPath: '$(Build.ArtifactStagingDirectory)'
            packagesToPush: '$(Build.ArtifactStagingDirectory)/packages/*.nupkg'
            nuGetFeedType: 'internal'
            publishVstsFeed: '9ee6d478-d288-47f7-aacc-f6e6d082ae6d/d1622942-d16f-48e5-bc83-96f4539e7601'
          - output: pipelineArtifact
            condition: always()
            targetPath: $(Build.ArtifactStagingDirectory)/logs
            artifactName: logs

        steps:
        - checkout: self
          clean: true
          submodules: true

        - task: DeleteFiles@1
          displayName: 🟣Delete files from bin
          inputs:
            SourceFolder: bin
            Contents: '**/*'

        - task: UseDotNet@2
          displayName: 🟣Install .NET Sdk
          inputs:
            useGlobalJson: true

        - task: DotNetCoreCLI@2
          displayName: 🟣dotnet restore
          inputs:
            command: custom
            custom: restore
            projects: |
              **\*.sln

        - task: DotNetCoreCLI@2
          displayName: 🟣dotnet build
          inputs:
            command: 'build'
            projects: |
              src\source-indexer.sln
              src\SourceBrowser\SourceBrowser.sln
            arguments: '/p:PackageOutputPath=$(Build.ArtifactStagingDirectory)/packages /p:EnableDebugLogging=true'

        # Skipping index build and website deployment - tools-only build

        - task: CopyFiles@2
          displayName: Copy binlogs for upload
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)'
            Contents: |
              **/*.binlog
            TargetFolder: $(Build.ArtifactStagingDirectory)/logs/src
            CleanTargetFolder: false
          continueOnError: true
          condition: succeededOrFailed()
