name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Restore source-indexer.sln
      run: dotnet restore src/source-indexer.sln
    - name: Restore SourceBrowser.sln
      run: dotnet restore src/SourceBrowser/SourceBrowser.sln
    - name: Build & test source-indexer.sln
      run: dotnet test --no-restore src/source-indexer.sln
    - name: Build & test SourceBrowser.sln
      run: dotnet test --no-restore src/SourceBrowser/SourceBrowser.sln
